### ISSUE TITLE
Remove or adjust G006

### ISSUE THREAD

**Issue by pcaversaccio** [byterocket/c4-common-issues#4]
# Remove or adjust: G006 - `immutable` for OpenZeppelin `AccessControl`'s Roles Declarations

Since Solidity version [`0.6.12`](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0612-2020-07-22) the `keccak256` of string literals are treated specially and the hash is evaluated at compile time. It's not even necessary to have optimizations enabled.

## Severity

Which severity would you assign to this Issue?

- [x] Gas Optimization
- [ ] Non-Critical
- [ ] Low Risk
- [ ] Med Risk
- [ ] High Risk

**Comment by pmerkleplant** [comment]
Many thanks for raising the Issue! ❤️ 
I added a warning that this optimization is only valid for solc versions `<0.6.12`, see this [commit](https://github.com/byterocket/c4-common-issues/commit/ef189076a2dfd9ed2013416b6573ceae7a3e82ee).

And please excuse the late response, the notification got lost in my inbox 😢
