### ISSUE TITLE
`iszero(x)` instruction is more gas efficient than `x == 0`

### ISSUE THREAD

**Issue by pcaversaccio** [byterocket/c4-common-issues#5]
# The `iszero(x)` instruction is more gas efficient than `x == 0`

## Severity

Which severity would you assign to this Issue?

- [x] Gas Optimization
- [ ] Non-Critical
- [ ] Low Risk
- [ ] Med Risk
- [ ] High Risk

## Description

With the use of the EVM dialect (=Yul), zero checking can be made more efficient via inline assembly.

## Example

🤦 Bad:
```solidity
/// @dev Consumes ~21812 gas on average.
function foo(uint256 x) external pure returns (bool result) {
    return x == 0;
}
```

🚀 Good:
```solidity
/// @dev Consumes ~21787 gas on average.
function bar(uint256 x) external pure returns (bool result) {
    assembly {
        result := iszero(x)
    }
}
```

## Background Information
- https://twitter.com/PaulRBerg/status/1521094594833915904

**Comment by pcaversaccio** [comment]
Tagging @pmerkleplant so it won't get forgotten :)

**Comment by pmerkleplant** [comment]
Thanks for raising the Issue!

Unfortunately, I'm not able to get any gas savings when trying this locally. I created two contracts with function `foo`, one using `iszero` and the other one with the built-in `==`. Both seem to create identical assembly code. I checked with solidity versions `0.8.10` and `0.8.13` and used foundry for gas reports.

The example in the linked Twitter feed is erroneous for testing gas savings because both functions are part of the same contract and the function signatures change the result. All else equal, the function with the lower function signature will use less gas because the function dispatching finds it faster, due to the function order being from lower signature to higher.

Checking `cast sig "foo(uint)"` and `cast sig "bar(uint)"` giving `0x2fbebd38` and `0x0423a132` seems to support this.

However, would love to be proven wrong! Did you manage to find gas savings locally with any solidity version?

**Comment by pcaversaccio** [comment]
Thanks for your feedback! I quickly tested everything using Remix in the following manner (I'm aware of the Solidity dispatch code and its potential associated gas costs, that's why I always test as follows):

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.13;

contract GasTesting {
    function foo(uint256 x) external view returns (bool result, uint256 gasUsed) {
        uint256 startGas = gasleft();
        result = (x == 0);
        gasUsed = startGas - gasleft();
        return (result, gasUsed);
    }

    function bar(uint256 x) external view returns (bool result, uint256 gasUsed) {
        uint256 startGas = gasleft();
        assembly {
            result := iszero(x)
        }
        gasUsed = startGas - gasleft();
        return (result, gasUsed);
    }
}
```

Now if compile, deploy and test both functions there will be no difference in case you **enabled** the optimizer:
![image](https://user-images.githubusercontent.com/25297591/166703333-7fc328e7-9c53-4602-bb98-2a38465cd3dc.png)

However, if you **disable** the optimizer (I used 200 runs) for the compilation, there will be an additional 3 gas charged by `foo`:
![image](https://user-images.githubusercontent.com/25297591/166703479-e335efe5-5402-45f6-b26e-c19932310ddb.png)

So now the question is whether there must be a general recommendation for enabling the optimizer?

**Comment by pcaversaccio** [comment]
You can also reproduce this result by naming both functions equally (hence no dispatch issue here) and commenting one of both functions out for the compilation & deployment.

If you follow this way, using `0` as the argument for the function, you will get the following execution costs (I used `foo` for the naming):
- 21,784 gas using the high-level Solidity version (optimizer disabled)
- 21,781 gas using the Assembly version (optimizer disabled)

**Comment by pmerkleplant** [comment]
```solidity
uint startGas = gasleft();
// ...
uint gasUsed = startGas - gasleft();
```
That's a cool trick! Prevents having to create two contracts each time. Thanks for sharing ❤️ 

> So now the question is whether there must be a general recommendation for enabling the optimizer?

I don't think we should advocate including that as an issue. Obviously, it is a valid recommendation, but also so generic that you can raise it in every contest. Furthermore, auditors/wardens do not have guarantees whether the recommendation was implemented.

Therefore, I tend to not include this optimization in the repo. However, I will share this Issue in the C4 community and ask for feedback. Will keep this Issue open until there is some consensus from the community.

And again, many thanks for raising the issue and taking the time to answer! 👍

**Comment by pcaversaccio** [comment]
@pmerkleplant yeah agreed - let's wait for the feedback from the community. If I come up with additional optimisations in the meantime, I will raise them here via issues. 

Just in case someone that is reading this issue is interested in a guide on gas optimisations, I'm the main author of [this](https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966) OpenZeppelin guide on gas optimisation tricks. Feel free to contribute!

**Comment by pmerkleplant** [comment]
Closing this as the c4 community seems to agree that this gas optimization is outside the scope of c4 contests, i.e. c4 contests audit codebases and not developer operations.

Link to Discord message [here](https://discord.com/channels/810916927919620096/810936719003090974/971682095938302032)

**Comment by pcaversaccio** [comment]
For the sake of completeness, the screenshot: 
![image](https://user-images.githubusercontent.com/25297591/168614417-76a7e8d2-4914-4331-975f-8431db08bac7.png)
